build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
                    - php ./vendor/bin/phpunit --configuration phpunit.xml


checks:
    php:
        phpunit_assertions: true

coding_style:
    php: {  }
filter: {  }